### ISSUE TITLE
IV Extractor fails on Priconne[JPN] v5.9.0

### ISSUE THREAD

**Issue by Sunev** [FabulousCupcake/pcr-exporter#32]
After Japan client visited https://api-priconne-redive.cygames.jp/check/check_agreement ,IV Extractor throws such error.
``````
Uncaught Exception:
Error: invalid ciphertext size (must be multiple of 16 bytes)
    at ModeOfOperationCBC.decrypt (E:\Github\pcr-exporter\node_modules\aes-js\index.js:475:19)
    at SWProxy.handler (E:\Github\pcr-exporter\app\plugins\iv-extractor.js:35:62)
    at SWProxy.emit (node:events:394:28)
    at E:\Github\pcr-exporter\app\proxy\proxy.js:71:14
    at E:\Github\pcr-exporter\node_modules\http-mitm-proxy\lib\proxy.js:1073:12
    at E:\Github\pcr-exporter\node_modules\http-mitm-proxy\node_modules\async\dist\async.js:2554:44
    at eachOfArrayLike (E:\Github\pcr-exporter\node_modules\http-mitm-proxy\node_modules\async\dist\async.js:503:13)
    at eachOf (E:\Github\pcr-exporter\node_modules\http-mitm-proxy\node_modules\async\dist\async.js:623:16)
    at awaitable (E:\Github\pcr-exporter\node_modules\http-mitm-proxy\node_modules\async\dist\async.js:211:32)
    at Object.eachLimit (E:\Github\pcr-exporter\node_modules\http-mitm-proxy\node_modules\async\dist\async.js:2657:16)
``````
This seems related to ```aesBody``` as a 196-bytes-long Buffer.
https://github.com/FabulousCupcake/pcr-exporter/blob/e46b814a1d5e0c3000a7bd6faa10412724df3c57/app/plugins/iv-extractor.js#L35

Please tell me if you need more information.

**Comment by FabulousCupcake** [comment]
I thought I wrote a reply weeks ago but looks like I didn't hit the send button 😔 

The project mainly focuses on the EN version; I don't play the JP version, so I don't think I can help with the updated encryption process in the other version — I'm not that experienced with reverse engineering and was only able to do it with the english version because it's very easy 😔

**Comment by Sunev** [comment]
Anyway, thanks for your reply.😊
